version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - sqlite_data:/app/app/database.db
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  sqlite_data: