version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development  # Change to production for production deployment
    restart: unless-stopped